### PR TITLE
slideoutmenu skitches

### PR DESCRIPTION
**Pull request by drumslayert**
#### SlideOutMenu sketches
- [x] `screen caps`
- [x] `desktop view` 
- [x] `tablet view` 
- [x] `mobile view` 
#### ResponsiveGrid sketching
- [x] `6-column-view`
- [x] `5-column-view`
- [x] `4-column-view`
- [x] `3-column-view`
- [x] `2-column-view`
- [x] `1-column-view`

### CODE REVIEW

**Comment by drumslayert** [comment]
Added both slideoutmenu and repsonsivegrid @s4dmw

**Comment by s4dmw** [comment]
@drumslayert - good progress! see comments below

##### Horizontal Slide Out Menu:

SlideOutMenu/desktop-default.png: 
-looks like you didnt mean to include this one. delete?

SlideOutMenu/specs/desktop-default.png:  looks good

SlideOutMenu/specs/desktop-active.png: 
-might be worth mentioning the faint border around each grid item and that the background of the grid is a very light gray

SlideOutMenu/specs/tablet-default.png:
-it looks like only the menu categories have the little arrows. we'll need to figure out why/how.
-they are probably just links made to look like drop down choices

SlideOutMenu/specs/tablet-active.png: looks good

SlideOutMenu/specs/mobile-default.png: looks good

SlideOutMenu/specs/mobile-active.png: looks good

**Comment by s4dmw** [comment]
@drumslayert - comments on the cat grid

don't forget to link this PR in the issue comments for this project

##### Responsive Full Width Grid

ResponsiveGrid/specs/6-column-view_default.png:
-probably only need to show 1 or 2 rows of grids max...that many cats makes my eyes bleed
-in the future it might be worth putting a box around your main/grid area. just a nit picky thing though

ResponsiveGrid/specs/6-column-view-active.png: looks good...way less cats = better

ResponsiveGrid/specs/5-column-view.png: so...many....cats

ResponsiveGrid/specs/4-column-view.png: meow

ResponsiveGrid/specs/3-column-view.png: caaaaaaattttttttttssssssss

ResponsiveGrid/specs/2-column-view.png: reminds me of this:



ResponsiveGrid/specs/1-column-view.png: looks good

**Comment by drumslayert** [comment]
@s4dmw the empty SlideOutMenu/desktop-default.png is not in my local so i must of deleted it and it still got pushed or something.  Also made a few changes at your suggestion. Let me know and I'll merge.

**Comment by drumslayert** [comment]
https://github.com/TIY-Durham/2015-FALL-FEE/issues/414

**Pull request merged**
